### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by hexiaoshi2019** [chaozhankai/jd_scripts_2021#1]
大佬：请问docker是怎么部署呀？ 因为lxk0301 现在已经不更新了

**Comment by google-mirror** [comment]
不能部署了

https://gitter.im/jd_scripts/community

**Comment by chaozhankai** [comment]
> 大佬：请问docker是怎么部署呀？ 因为lxk0301 现在已经不更新了

用这个吧一直在更新的 https://github.com/shufflewzc/faker2
